### ISSUE TITLE
Present on project at D4G meetup - Wed Oct 18

### ISSUE THREAD

**Issue by jfnb** [ajah/nonprofitknowledge#2]
Mlenc to go

**Comment by GriffGeorge** [comment]
@mlenczner I've put together a deck for the generic D4G intro talk. I've got a slide to identify this project and you as the speaker who will introduce it -- should it be beside the "Powered by Data" logo, or the "Ajah" logo?

https://docs.google.com/presentation/d/1lEKTU2Naamo0melTeYjs2zeU8D_LCFzWQSegRnainLs/edit?usp=sharing

**Comment by mlenczner** [comment]
already responded but Ajah is the host of the project, but I'm sure that Powered by Data will be involved somehow.

**Comment by GriffGeorge** [comment]
This was completed.
